//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalApartmentDetails
    {
        public int AdditionalApartmentID { get; set; }
        public Nullable<int> IdApartment { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> Terrace { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<int> Recommendations { get; set; }
        public string AdditionalDescription { get; set; }
    
        public virtual ApartmentDetails ApartmentDetails { get; set; }
    }
}
