//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.ApartmentDetails = new HashSet<ApartmentDetails>();
            this.Dates = new HashSet<Dates>();
        }
    
        public int ApartmentId { get; set; }
        public Nullable<int> RentorId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> NumberOfBeds { get; set; }
        public Nullable<int> NumberOfAirConditioners { get; set; }
        public Nullable<bool> IsRentingImmediately { get; set; }
        public string ImmediatePrice { get; set; }
        public string Price { get; set; }
        public string DiscountPercentages { get; set; }
        public string NumberOfDiscountDays { get; set; }
        public string Img { get; set; }
    
        public virtual RentorDetails RentorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentDetails> ApartmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dates> Dates { get; set; }
    }
}
