//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApartmentDetails()
        {
            this.Recommendations = new HashSet<Recommendations>();
        }
    
        public int ApartmentDetailsID { get; set; }
        public Nullable<int> IdApartment { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> DisableAccess { get; set; }
        public Nullable<int> Porch { get; set; }
        public string ImageSrc { get; set; }
        public Nullable<bool> Parking { get; set; }
        public string AdditionalDescription { get; set; }
        public Nullable<int> Crib { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recommendations> Recommendations { get; set; }
    }
}
