//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApartmentDetails()
        {
            this.AdditionalApartmentDetails = new HashSet<AdditionalApartmentDetails>();
            this.DateAvailable = new HashSet<DateAvailable>();
            this.RentedApartment = new HashSet<RentedApartment>();
        }
    
        public int ApartmentID { get; set; }
        public Nullable<int> RentorId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public Nullable<bool> DisabledAccess { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> NumberOfBeds { get; set; }
        public Nullable<int> NumberOfAirConditioners { get; set; }
        public Nullable<bool> IsRentingImmediately { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalApartmentDetails> AdditionalApartmentDetails { get; set; }
        public virtual RentorDetails RentorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DateAvailable> DateAvailable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentedApartment> RentedApartment { get; set; }
    }
}
