//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApartmentsForRentEntities : DbContext
    {
        public ApartmentsForRentEntities()
            : base("name=ApartmentsForRentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<ApartmentDetails> ApartmentDetails { get; set; }
        public virtual DbSet<Dates> Dates { get; set; }
        public virtual DbSet<Recommendations> Recommendations { get; set; }
        public virtual DbSet<RentorDetails> RentorDetails { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
