//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendations
    {
        public int RecommendationsId { get; set; }
        public Nullable<int> IdApartmentDetails { get; set; }
        public string Recommendations1 { get; set; }
    
        public virtual ApartmentDetails ApartmentDetails { get; set; }
    }
}
