export class SearchAppeartment {
    City:string;
    NumChildren:number;
    StartDate:Date;
    EndDate:Date;
    PriceFrom:string;
    PriceTo:string;
    DisableAccess:boolean;
    Pool:boolean;
    Porch:boolean;
    Parking:boolean;
    Crib:boolean;
    Elevator:boolean;
    ImmediatelyRenting:boolean;
    NumberOfAirConditioners:number;
    NumberOfRooms:number;  
    minPrice:number;
    maxPrice:number
}